apiVersion: apps/v1
kind: Deployment
metadata:
  name: reto2-front-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      containers:
      - name: reto2-front
        image: studentroauis/reto2-front:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reto2-back-out-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
      nodePort: 30420
