apiVersion: apps/v1
kind: Deployment
metadata:
  name: reto2-front-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
    spec: 
      containers:
      - name: reto2-front
        image: studentroauis/reto2-front:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:1.3.0
        args:
           - -nginx.scrape-uri=http://localhost:80/stub_status
        ports:
          - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: reto2-front-out-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
      nodePort: 30420
