services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
