apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'
  
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: default-receiver
      routes:
      - match:
          severity: critical
        receiver: alert-receiver
      - match: 
          severity: warning
        receiver: alert-receiver
      - match:
          severity: info
        receiver: info-receiver

    receivers:
    - name: default-receiver
      slack_configs:
        - send_resolved: true
          channel: '#alertas'
          text: '{{ template "slack.default.text" . }}'
          title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    - name: info-receiver
      slack_configs:
        - send_resolved: true
          channel: '#info'
          text: '{{ template "slack.default.text" . }}'
          title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    - name: alert-receiver
      slack_configs:
        - send_resolved: true
          channel: '#alertas'
          text: '{{ template "slack.default.text" . }}'
          title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"